language: generic
branches:
  only:
    - master
cache:
  directories:
    - vendor
services:
  - docker
install:
  - make bootstrap
script:
  - make test-cover build docker-build
after_success:
  - bash <(curl -s https://codecov.io/bash)
