name: workflow-manager
home: https://github.com/deisthree/workflow-manager
version:  <Will be populated by the ci before publishing the chart>
description: "Deis Workflow Manager: Cluster First Aid"
maintainers:
  - name: Deis Team
    email: engineering@deis.com
